#!/usr/bin/env node
// Builds js/font5x8.js from a JSON map of { char: [8 rows of 5 chars] }.
// Usage: node tools/build-font.mjs glyphs.json
// Glyphs are stored as 5 column bytes; bit r (0 = top) is row r. This is the
// same layout classic HD44780 / GFX fonts use, and it decodes with one shift.
import fs from 'node:fs';

const src = process.argv[2];
if (!src) { console.error('usage: build-font.mjs glyphs.json'); process.exit(1); }
const glyphs = JSON.parse(fs.readFileSync(src, 'utf8'));
const entries = Object.entries(glyphs).sort((a, b) => a[0].codePointAt(0) - b[0].codePointAt(0));
const lines = [];
for (const [ch, rows] of entries) {
  if (rows.length !== 8 || rows.some(r => !/^[.#]{5}$/.test(r))) throw new Error(`bad glyph ${JSON.stringify(ch)}`);
  const cols = [];
  for (let c = 0; c < 5; c++) {
    let bits = 0;
    for (let r = 0; r < 8; r++) if (rows[r][c] === '#') bits |= 1 << r;
    cols.push('0x' + bits.toString(16).padStart(2, '0'));
  }
  lines.push(`  ${JSON.stringify(ch)}: [${cols.join(', ')}],`);
}
const out = `// font5x8.js — classic 5×8 dot-matrix font (HD44780 style), generated by tools/build-font.mjs.
// Each glyph is 5 column bytes; bit r (0 = top row) of a byte is LED row r.
// Row 7 is the descender row, used only by g j p q y , ; .
export const GLYPH_W = 5;
export const GLYPH_H = 8;
export const GLYPHS = {
${lines.join('\n')}
};
`;
fs.writeFileSync(new URL('../js/font5x8.js', import.meta.url), out);
console.log(`wrote js/font5x8.js with ${entries.length} glyphs`);
